### PR TITLE
fix: allow only numerical input for uint256 field

### LINKED ISSUE #212: uint256 input should not throw errors with string input
Entering a text value and trying to parse it leads to following error:

image

~I propose to only allow numerical input when type is uint256~

### PR DESCRIPTION
**Pull request by sverps**
Fixes #212

### CODE REVIEW

File: packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx [hunk 1]
```diff
@@ -60,6 +60,7 @@ const InputUI = ({ setForm, form, stateObjectKey, paramType }: TInputUIProps) =>
               formUpdate[event.target.name] = contractFunctionArgument;
               setForm(formUpdate);
             }}
+            type={paramType.type === "uint256" ? "number" : undefined}
```
Comment (rin-st) [inline packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx:63]: do we need that arrows?

Screenshot 2023-02-25 at 19 14 40

Comment (technophile-04) [reply packages/nextjs/components/scaffold-eth/Contract/InputUI.tsx:63]: ++ vote to remove it

**Comment by technophile-04** [comment]
Also a small nitpick, I think it was introduced in #206 

The `*` is not centered correctly aligned: 
Screenshot 2023-02-25 at 10 27 04 PM

**Comment by sverps** [comment]
> The `*` is not centered correctly aligned:

I noticed the method to align the asterisk was to place it at flex-end, to sort of 'simulate' being centered. This means the fields with `#` were a bit off-center. I fixed it by using a vertically centered alternative to the asterisk.

Additionally, rather than forcing numerical input, I aligned the behavior with that of `TxValueInput` and when the value is invalid (e.g. string input for uint256 field), the form now shows a red border indicating an issue.

**Comment by technophile-04** [comment]
Tysm @sverps love the new approach and it works great !!! lol sorry for being PITA

File: packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx [hunk 2]
```diff
@@ -83,14 +83,14 @@ const TxValueInput = ({ setTxValue, txValue }: { setTxValue: Dispatch<SetStateAc
           data-tip="Multiply by 10^18 (wei)"
         >
           <button
-            className="cursor-pointer text-xl font-semibold pt-1 px-4 text-accent"
+            className="cursor-pointer text-l font-semibold px-4 text-accent"
```
Comment (technophile-04) [inline packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx:86]: just small changes, we can change `text-l` -> `text-xl`.....I think it was added by mistake since `text-l` doesn't exist in tailwind

Also I think we should keep it `text-xl` instead of removing it I like big symbols

File: packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx [hunk 3]
```diff
@@ -98,8 +98,8 @@ export const UintToEtherConverter = ({ form, setForm, stateObjectKey }: IUtility
   }, [form, setForm, stateObjectKey]);
 
   return (
-    <div className="cursor-pointer text-xl font-semibold px-4 text-accent" onClick={convertEtherToUint}>
-      *
+    <div className="cursor-pointer text-l font-semibold px-4 text-accent" onClick={convertEtherToUint}>
```
Comment (technophile-04) [inline packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx:101]: same `text-l` -> `text-xl`

File: packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx (hunk 2 above)
Comment (sverps) [reply packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx:86]: Oops, wanted to put `text-lg`. I modified it to keep the sizing of the asterisk about the same, but if everyone is fine with a larger character, we can keep it on text-xl as well. Either works for me.

File: packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx (hunk 3 above)
Comment (sverps) [reply packages/nextjs/components/scaffold-eth/Contract/utilsDisplay.tsx]: fixed

**Comment by sverps** [comment]
Here's what the asterisk will look like after this PR:
image

File: packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx (hunk 2 above)
Comment (technophile-04) [reply packages/nextjs/components/scaffold-eth/Contract/utilsComponents.tsx]: cc @carletex for `xl` and `lg`... both look great to me, maybe he can change it while merging

**Review by technophile-04 — APPROVED** [review]
